pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'pipeline {
    agent {
        docker {
            // Menggunakan Docker image 'maven:3.9.0'
            image 'maven:3.9.0'
            // Mengatur volume untuk cache Maven
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                // Menjalankan perintah Maven untuk membersihkan dan membangun proyek
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                // Menjalankan perintah Maven untuk menjalankan pengujian
                sh 'mvn test'
            }
            post {
                always {
                    // Menghasilkan laporan pengujian JUnit
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Manual Approval') {
            // Tahap persetujuan manual sebelum Deliver
            steps {
                input message: 'Apakah Anda yakin ingin melanjutkan ke tahap Deliver?'
            }
        }
        stage('Deliver') {
            steps {
                // Menunggu selama 1 jam sebelum melanjutkan ke tahap Deliver
                sleep time: 1, unit: 'HOURS'
                // Menjalankan skrip deliver.sh untuk melakukan pengiriman
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            input message: 'Lanjutkan ke tahap Deploy?'
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
            sleep time: 1, unit: 'MINUTES'
        }
    }
}
